version: "master-{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "200"

clone_folder: c:\projects\openssl

branches:
  only:
    - master

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem install bundler --no-ri --no-rdoc
  - bundler --version
  - cp C:\Ruby21\DevKit\mingw\bin\bsdtar.exe C:\Ruby21\DevKit\bin\tar.exe

build_script:
  - bundle install || bundle install || bundle install
  - C:\Ruby21\DevKit\devkitvars.bat
  - echo %PATH%
  - bundle exec rake build
